# Generated by Django 3.1.7 on 2021-04-04 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Shift start date')),
                ('arrival_time', models.TimeField(verbose_name='Shift start time')),
                ('departure_time', models.TimeField(verbose_name='Shift end time')),
                ('repeat', models.CharField(choices=[('None', 'None'), ('Daily', 'Daily'), ('Weekly', 'Weekly')], default='None', max_length=10, verbose_name='Select Repeat Type')),
                ('shift_availability', models.CharField(choices=[('Morning Shift', 'Morning Shift - 5am to 9am')], default='Morning Shift', max_length=15, verbose_name='Select shift')),
                ('monday', models.BooleanField(default=False, verbose_name='Mon')),
                ('tuesday', models.BooleanField(default=False, verbose_name='Tue')),
                ('wednesday', models.BooleanField(default=False, verbose_name='Wed')),
                ('thrusday', models.BooleanField(default=False, verbose_name='Thr')),
                ('friday', models.BooleanField(default=False, verbose_name='Fri')),
                ('saturday', models.BooleanField(default=False, verbose_name='Sat')),
                ('sunday', models.BooleanField(default=False, verbose_name='Sun')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.client', verbose_name='Shift Created By')),
            ],
        ),
    ]
