# Generated by Django 3.1.7 on 2021-04-04 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0002_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Shift Created By'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_availability',
            field=models.CharField(choices=[('Morning Shift - 5am to 9am', 'Morning Shift - 5am to 9am')], default='Morning Shift - 5am to 9am', max_length=50, verbose_name='Select shift'),
        ),
    ]
